### ISSUE TITLE
Not actively polling for updates

### ISSUE THREAD

**Issue by 23534664** [jaroschek/home-assistant-eaton-ups#16]
How do you set up the polling rate as this only updates the sensors once and does not automaticaly pole the sensors.

**Comment by 23534664** [comment]
![image](https://github.com/jaroschek/home-assistant-eaton-ups/assets/109723530/dd8e066a-a527-4f9e-a72d-2ac0a3da12d4)

**Comment by 23534664** [comment]
Logger: homeassistant
Source: custom_components/eaton_ups/sensor.py:196
integration: Eaton UPS ([documentation](https://github.com/jaroschek/home-assistant-eaton-ups), [issues](https://github.com/jaroschek/home-assistant-eaton-ups/issues))
First occurred: 2:47:20 PM (21 occurrences)
Last logged: 3:07:48 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 414, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/eaton_ups/sensor.py", line 132, in _handle_coordinator_update
    super().async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1009, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1015, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 543, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eaton_ups/sensor.py", line 196, in native_value
    datetime.strptime(self._attr_native_value, "%m/%d/%Y")
  File "/usr/local/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%m/%d/%Y'

**Comment by jaroschek** [comment]
@23534664 As documented by your error log the date parsing for the sensor `Battery Last Replaced` was causing an error.

Thus the whole coordinator update run seems to stall.

I have now secured the date parsing and return `None` in case of an error to show the sensor value as `Unknown`.

Please try the new pre-release: https://github.com/jaroschek/home-assistant-eaton-ups/releases/tag/1.2.1-rc1

**Comment by 23534664** [comment]
Thanks, it is fix now, thanks allot @jaroschek.
