### ISSUE TITLE
Setup failed for custom integration 'eaton_ups': Unable to import component: No module named 'pyasn1.compat.octets'

### ISSUE THREAD

**Issue by reedy** [jaroschek/home-assistant-eaton-ups#32]
Seems to be some relevance to https://github.com/home-assistant/core/issues/125286

Seen after upgrading to 2024.10.0

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/src/homeassistant/homeassistant/components/brother/__init__.py", line 5, in <module>
    from brother import Brother, SnmpError
  File "/usr/local/lib/python3.12/site-packages/brother/__init__.py", line 13, in <module>
    from pysnmp.hlapi.asyncio import (
  File "/usr/local/lib/python3.12/site-packages/pysnmp/hlapi/__init__.py", line 7, in <module>
    from pysnmp.proto.rfc1902 import *
  File "/usr/local/lib/python3.12/site-packages/pysnmp/proto/rfc1902.py", line 8, in <module>
    from pysnmp.proto import rfc1155, error
  File "/usr/local/lib/python3.12/site-packages/pysnmp/proto/rfc1155.py", line 10, in <module>
    from pysnmp.proto import error
  File "/usr/local/lib/python3.12/site-packages/pysnmp/proto/error.py", line 9, in <module>
    from pysnmp import debug
  File "/usr/local/lib/python3.12/site-packages/pysnmp/debug.py", line 8, in <module>
    from pyasn1.compat.octets import octs2ints
ModuleNotFoundError: No module named 'pyasn1.compat.octets'
```

**Comment by lorenzo93** [comment]
I'm having the same issue.

**Comment by rodgorlabach** [comment]
Same issue here

`2024-10-03 09:10:38.462 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'eaton_ups': Unable to import component: No module named 'pyasn1.compat.octets'
File "/config/custom_components/eaton_ups/__init__.py", line 5, in <module>`

**Comment by Larosen** [comment]
Same issue here since 2024.10.0

**Comment by jaroschek** [comment]
I have updated th requirement for `pysnmp` to version 6.2.6 as in https://github.com/home-assistant/core/pull/126488.

You can try the new pre-release version: https://github.com/jaroschek/home-assistant-eaton-ups/releases/tag/1.2.2-rc1

But as quoted there this seems to not fix already 'messed up' installations. Though you may need to run some cli commands: https://github.com/home-assistant/core/issues/125286#issuecomment-2391979102

**Comment by jaroschek** [comment]
To avoid future problems because of different versions of `pysnmp` I have now removed the direct requirement for `pysnmp` from my custom integration.

Instead the integration already has defined `after_dependencies` to the core integration `snmp` that itself requires `pysnmp`.

This latest change is now available to test in the pre-release https://github.com/jaroschek/home-assistant-eaton-ups/releases/tag/1.2.2-rc2

**Comment by rodgorlabach** [comment]
1.2.2.rc2 fixed the issue!

**Comment by reedy** [comment]
Thanks!

**Comment by ArturZurawski** [comment]
Hello, I'm running HA in docker 2024.11.1, eaton plugin is in 1.2.3. Is there anything I should do to make it work?
