### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by MrGreenGuyDK** [jaroschek/home-assistant-eaton-ups#41]
Hi Jaroschek.

Thanks for this :-) - question , the entities is not updated unless component is reloaded , is there a setting for the snmp pull somewhere or do i have to automate it somehow ?

Best Regards.

**Comment by wiesner-philipp** [comment]
Hey!

Same problem here, the entities arn't updated. Deleting the device and readding it forces the plugin to pull fresh data.

```
Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:608
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 08:07:24 (1 Vorkommnisse)
Zuletzt protokolliert: 08:07:24

Error adding entity sensor.eaton_5px_1500_input_status for domain sensor with platform eaton_ups
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 927, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1384, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 614, in state
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Sensor sensor.eaton_5px_1500_input_status provides state value '0.0', which is not in the list of options provided
```
```
Logger: homeassistant
Quelle: components/sensor/__init__.py:614
Erstmals aufgetreten: 08:08:23 (115 Vorkommnisse)
Zuletzt protokolliert: 10:02:23

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 267, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 478, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/config/custom_components/eaton_ups/sensor.py", line 133, in _handle_coordinator_update
    super().async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 614, in state
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Sensor sensor.eaton_5px_1500_input_status provides state value '0.0', which is not in the list of options provided
```

These are the only errors I get in relation to this problem.

**Comment by yvosound** [comment]
hi there, here the same problem.
sensors won't update.
i did a ugly workaround: a automation that every 10 seconds reloads the complete intergration.
firtst attempt to do a automation that update's the induvidual ententities doesn't work.

**Comment by gabzqc1** [comment]
- [ ] same issue here, since install last July. Any news or update?

**Comment by lorenzo93** [comment]
2025.4.2, updated today, exactly the same error.
